"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages

NAME = 'Incantus'
VERSION = '0.1'

DATA_FILES = [] #['./data', './data/'+NAME+'.icns']
APP = ['src/Incantus.py']
OPTIONS = dict(compressed=True,
               optimize=1)
setup (name=NAME,
      version=VERSION,
      description='',
      author_email='incantus1@gmail.com',
      package_dir={'': 'src'},
      packages=find_packages(),
      data_files=DATA_FILES,
      #options = OPTIONS
)
