"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import py2app

NAME = 'Incantus'
VERSION = '0.1'

plist = dict(
    CFBundleIconFile=NAME+'.icns',
    CFBundleName=NAME,
    CFBundleShortVersionString=VERSION,
    CFBundleGetInfoString=' '.join([NAME, VERSION]),
    CFBundleExecutable=NAME,
    CFBundleIdentifier='net.incantus',
)

APP = ['src/Incantus.py']
DATA_FILES = ['./small_deck.txt', './data', './data/'+NAME+'.icns']
OPTIONS = dict(argv_emulation=False,
               plist=plist,
               compressed=True,
               optimize=1,
               #site-packages=True,
               includes=["pyglet.media.drivers.openal"])

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
