"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import py2app

NAME = 'MtG'
VERSION = '0.1'

plist = dict(
    CFBundleIconFile=NAME+'.icns',
    CFBundleName=NAME,
    CFBundleShortVersionString=VERSION,
    CFBundleGetInfoString=' '.join([NAME, VERSION]),
    CFBundleExecutable=NAME,
    CFBundleIdentifier='net.infinite8s.mtg',
)

APP = ['src/MtG.py']
DATA_FILES = ['./data', './data/'+NAME+'.icns']
OPTIONS = dict(argv_emulation=True, plist=plist)

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
